# -*- coding: utf-8 -*-
AREAS = [
{"slug":"panaji","name":"Panaji","region":"North","img":"loc-panaji.jpg",
 "meta":"Digital marketing agency serving Panaji (Panjim), Goa — local SEO, Google Ads, social media, web design and branding for the capital's businesses, offices and hospitality.",
 "intro":"As Goa's capital and commercial heart, Panaji is one of the most competitive — and rewarding — markets in the state. We help Panjim businesses get found, get chosen and grow online.",
 "body":["Panaji (Panjim) concentrates offices, retail, restaurants, hospitality and professional services in a compact, high-traffic area. Customers here — residents and visitors alike — search on Google and Maps before they decide, so visibility in local results is decisive.",
   "Sanctify builds Panaji businesses a complete local presence: an optimised Google Business Profile, local SEO that wins 'near me' searches, a fast conversion-focused website, and social and paid campaigns tuned to the capital's audience."],
 "industries":["Restaurants, cafes &amp; bars","Offices &amp; professional services","Retail &amp; boutiques","Hotels &amp; guesthouses"],
 "nearby":[("porvorim","Porvorim"),("mapusa","Mapusa"),("candolim","Candolim")],
 "faqs":[["Do you work with small businesses in Panaji?","Yes — from single-location cafes and clinics to offices and retailers. We tailor scope and budget to your goals, starting with the highest-ROI local SEO and Google Business Profile work."],
   ["How do you help Panaji businesses rank on Google Maps?","We optimise your Google Business Profile, build consistent local citations, create location-relevant content, and generate a steady flow of reviews so you appear for 'near me' searches across Panjim."],
   ["Can you handle everything from strategy to execution?","Yes. As a full-service agency we cover SEO, web design, social media, Google &amp; Meta ads and branding — so your Panaji marketing is coordinated under one roof."]]},

{"slug":"calangute","name":"Calangute","region":"North","img":"loc-calangute.jpg",
 "meta":"Digital marketing for Calangute, Goa — SEO, social media and direct-booking websites for hotels, restaurants, shacks and tourist businesses in Goa's busiest beach belt.",
 "intro":"Calangute is Goa's busiest beach destination, and competition for every tourist is fierce. We help Calangute hotels, restaurants and shacks stay visible when travellers are searching — and convert that attention into bookings.",
 "body":["In Calangute the customer journey is almost entirely digital: travellers search, compare on Google and Instagram, read reviews and book on their phones. If your property isn't fast to find, easy to trust and simple to book, that guest goes to a competitor.",
   "We build Calangute businesses a direct-booking engine — a fast mobile-first website, strong local SEO and Google Business Profile presence, a living social feed, and seasonal paid campaigns to fill quieter weeks and reduce OTA dependence."],
 "industries":["Hotels &amp; resorts","Beach shacks &amp; restaurants","Water sports &amp; activities","Retail &amp; nightlife"],
 "nearby":[("baga","Baga"),("candolim","Candolim"),("anjuna","Anjuna")],
 "faqs":[["Can you help my Calangute hotel get more direct bookings?","Yes. By strengthening your direct-booking website, local SEO, Google Business Profile and social presence, we shift reservations to your own channels and reduce the commissions OTAs charge."],
   ["How do you handle Goa's seasonality in Calangute?","We plan campaigns around the calendar — building visibility ahead of peak season and running targeted offers to fill the quieter monsoon and shoulder months."],
   ["Do you work with beach shacks and restaurants?","Absolutely. We help Calangute shacks and restaurants win the Google Map Pack and 'near me' searches, build reviews, and run mouth-watering social and ad campaigns that drive footfall."]]},

{"slug":"baga","name":"Baga","region":"North","img":"loc-baga.jpg",
 "meta":"Digital marketing for Baga, Goa — social media, ads and websites for nightlife venues, restaurants, water sports and hotels in one of North Goa's liveliest destinations.",
 "intro":"Baga is North Goa's nightlife and dining hotspot. We help Baga venues, restaurants and activity operators stand out to the tourists searching and scrolling before they arrive.",
 "body":["Baga's audience is young, social and mobile-first — they discover venues on Instagram and Google, compare reviews, and decide fast. Visibility and scroll-stopping content are everything here.",
   "Sanctify helps Baga businesses win with Reels-led social media, strong local SEO, review generation and targeted ads for events, offers and peak nights — turning attention into footfall and bookings."],
 "industries":["Nightlife &amp; clubs","Restaurants &amp; bars","Water sports &amp; activities","Hotels &amp; hostels"],
 "nearby":[("calangute","Calangute"),("anjuna","Anjuna"),("candolim","Candolim")],
 "faqs":[["Do you run social media for Baga nightlife venues?","Yes — we create Reels-led content and run event and offer campaigns that reach the right tourists and locals, keeping your venue top-of-mind on busy nights."],
   ["Can you promote events and offers quickly?","We run agile Meta and Google campaigns for events, happy hours and seasonal offers, targeted to nearby tourists and interest audiences for fast, measurable footfall."],
   ["How do reviews help my Baga business?","Reviews drive both your Google Map Pack ranking and a tourist's choice. We set up simple systems to earn a steady flow of genuine reviews."]]},

{"slug":"candolim","name":"Candolim","region":"North","img":"loc-candolim.jpg",
 "meta":"Digital marketing for Candolim, Goa — premium SEO, web design and social media for upscale hotels, restaurants and retail serving Candolim's affluent visitors.",
 "intro":"Candolim attracts a more premium, affluent visitor. We help Candolim hotels, restaurants and boutiques present a polished digital presence that matches their positioning and converts.",
 "body":["Candolim's guests expect quality — and judge a business by its website, photos and reviews before booking. A premium experience online is essential to win this audience.",
   "We craft Candolim brands a refined website, strong local SEO and Google Business Profile presence, elegant social content and precise paid campaigns that attract higher-value guests and direct bookings."],
 "industries":["Premium hotels &amp; resorts","Fine dining","Boutique retail","Wellness &amp; spa"],
 "nearby":[("calangute","Calangute"),("baga","Baga"),("panaji","Panaji")],
 "faqs":[["Can you build a premium website for my Candolim hotel?","Yes — fast, elegant, mobile-first sites with direct-booking and strong visuals that match your premium positioning and convert affluent guests."],
   ["How do you attract higher-value guests?","Through refined branding, quality photography, targeted campaigns and reputation management that position your business as the premium choice in Candolim."],
   ["Do you manage social media for upscale brands?","We produce on-brand, aspirational content and manage your feed so it consistently reflects the quality of your business."]]},

{"slug":"mapusa","name":"Mapusa","region":"North","img":"loc-mapusa.jpg",
 "meta":"Digital marketing for Mapusa, Goa — local SEO, Google Business Profile and websites for shops, services and local businesses in North Goa's busy market town.",
 "intro":"Mapusa is North Goa's bustling market and services town, driven by resident (not just tourist) demand. We help Mapusa businesses win local customers searching for what they offer.",
 "body":["Mapusa's customers are largely locals searching for shops, clinics, services and trades. Winning 'near me' searches and the Google Map Pack is the highest-impact marketing a Mapusa business can do.",
   "We optimise your Google Business Profile, build local SEO and citations, create a simple conversion-focused website, and run local offers — so nearby customers find and choose you first."],
 "industries":["Retail &amp; wholesale","Clinics &amp; healthcare","Local services &amp; trades","Restaurants"],
 "nearby":[("porvorim","Porvorim"),("panaji","Panaji"),("assagao","Assagao")],
 "faqs":[["Is digital marketing worth it for a local Mapusa shop?","Yes. Most customers search Google before visiting. A strong Google Business Profile and local SEO put you in front of nearby buyers at the moment they're deciding."],
   ["Do I need a website if most customers are local?","A simple, fast website builds trust and captures enquiries — and it powers your Google presence. Even a one-page site with click-to-call and directions helps."],
   ["How do you help clinics and services in Mapusa?","We combine trust-building websites, local SEO for 'near me' searches and Google review systems so patients and clients find and choose you easily."]]},

{"slug":"porvorim","name":"Porvorim","region":"North","img":"loc-porvorim.jpg",
 "meta":"Digital marketing for Porvorim, Goa — SEO, web design and lead generation for offices, real estate, clinics and service businesses in North Goa's commercial-residential belt.",
 "intro":"Porvorim is a growing commercial and residential hub. We help Porvorim offices, real estate, clinics and service businesses generate qualified local leads online.",
 "body":["Porvorim blends offices, showrooms, clinics and residential demand. Businesses here compete for both local residents and wider North Goa customers — making search visibility and lead capture crucial.",
   "Sanctify delivers Porvorim businesses local SEO, conversion-focused websites, Google &amp; Meta lead-gen campaigns and Google Business Profile optimisation, with every enquiry tracked to its source."],
 "industries":["Real estate &amp; property","Offices &amp; B2B services","Clinics &amp; healthcare","Showrooms &amp; retail"],
 "nearby":[("panaji","Panaji"),("mapusa","Mapusa"),("candolim","Candolim")],
 "faqs":[["Can you generate leads for my Porvorim business?","Yes — we run targeted Google and Meta campaigns with dedicated landing pages and tracking, so you get qualified enquiries and know exactly which campaigns produce them."],
   ["Do you help real estate businesses in Porvorim?","We build high-converting property landing pages, run buyer-intent campaigns (including NRI targeting) and set up fast lead capture and follow-up."],
   ["How soon can we expect results?","Paid campaigns can generate leads within days; local SEO builds over 3–4 months and compounds. We usually run both for speed and long-term value."]]},

{"slug":"anjuna","name":"Anjuna","region":"North","img":"loc-anjuna.jpg",
 "meta":"Digital marketing for Anjuna, Goa — social media, branding and websites for cafes, hostels, events and lifestyle brands in North Goa's bohemian hotspot.",
 "intro":"Anjuna is North Goa's bohemian, creative hub — famous for its flea market, cafes and events. We help Anjuna cafes, stays and lifestyle brands build a following and drive visits.",
 "body":["Anjuna's audience is young, international and highly social — they find places through Instagram, Reels and word of mouth. Strong visual branding and content are the currency here.",
   "We help Anjuna brands with standout branding, Reels-led social media, event promotion and local SEO so both travellers and the creative community discover and choose them."],
 "industries":["Cafes &amp; restaurants","Hostels &amp; stays","Events &amp; markets","Lifestyle &amp; wellness brands"],
 "nearby":[("baga","Baga"),("assagao","Assagao"),("morjim","Morjim")],
 "faqs":[["Do you specialise in social media for Anjuna cafes and brands?","Yes — we create the scroll-stopping, aesthetic content Anjuna's audience responds to, and grow engaged followings that translate into visits."],
   ["Can you help promote events and markets?","We run targeted event campaigns across Instagram and Google, reaching the right travellers and locals to drive attendance."],
   ["How important is branding in Anjuna?","Very — Anjuna's audience buys into a look and feel. Strong, consistent branding is what makes a cafe or brand memorable and shareable here."]]},

{"slug":"assagao","name":"Assagao","region":"North","img":"loc-assagao.jpg",
 "meta":"Digital marketing for Assagao, Goa — premium branding, web design and SEO for luxury villas, boutique stays and fine dining in North Goa's most upscale village.",
 "intro":"Assagao is North Goa's most upscale village — luxury villas, boutique stays and destination dining. We help premium Assagao brands look and perform as good as they are.",
 "body":["Assagao's clientele is affluent and design-conscious, including NRI and out-of-state buyers. Presentation, trust and a premium digital experience decide who wins their business.",
   "We craft Assagao brands refined identities, beautiful high-converting websites, elegant social content and precise campaigns — including targeting for premium real estate buyers researching remotely."],
 "industries":["Luxury villas &amp; real estate","Boutique stays","Fine dining","Design &amp; lifestyle brands"],
 "nearby":[("anjuna","Anjuna"),("mapusa","Mapusa"),("morjim","Morjim")],
 "faqs":[["Do you work with luxury villas and boutique brands in Assagao?","Yes — premium branding, photography-led websites and refined social content are our specialty for Assagao's upscale market."],
   ["Can you reach NRI and out-of-state property buyers?","We geo-target campaigns to the cities and countries where your buyers are, with messaging tailored to remote, high-value purchasers."],
   ["How do you keep everything on-brand?","We build a clear brand system — visuals, voice and templates — so every touchpoint feels consistently premium."]]},

{"slug":"morjim","name":"Morjim","region":"North","img":"loc-morjim.jpg",
 "meta":"Digital marketing for Morjim, Goa — websites, social media and SEO for beach resorts, wellness retreats and long-stay hospitality in North Goa's tranquil belt.",
 "intro":"Morjim is North Goa's calmer, wellness-oriented beach belt — resorts, yoga retreats and long-stay travellers. We help Morjim hospitality brands reach the right guests and fill rooms.",
 "body":["Morjim attracts wellness travellers, remote workers and long-stay guests who plan ahead and research thoroughly online. Content and visibility across the planning cycle are key.",
   "We help Morjim resorts and retreats with booking-focused websites, local SEO, calming on-brand social content and seasonal campaigns targeting wellness and long-stay audiences."],
 "industries":["Beach resorts","Yoga &amp; wellness retreats","Long-stay &amp; villas","Cafes &amp; restaurants"],
 "nearby":[("anjuna","Anjuna"),("assagao","Assagao"),("calangute","Calangute")],
 "faqs":[["Can you market a wellness retreat in Morjim?","Yes — we build calming, on-brand websites and content, and target wellness and long-stay travellers who plan trips well in advance."],
   ["Do you help attract long-stay and remote-worker guests?","We create content and campaigns around extended stays, workspace-friendly amenities and monthly rates to reach this growing audience."],
   ["How do you fill rooms off-season in Morjim?","Through content that keeps you visible, review generation, and targeted offers to wellness travellers and residents during quieter months."]]},

{"slug":"margao","name":"Margao","region":"South","img":"loc-margao.jpg",
 "meta":"Digital marketing agency for Margao (Madgaon), South Goa — local SEO, Google Ads, web design and branding for the commercial capital's shops, services and businesses.",
 "intro":"Margao (Madgaon) is South Goa's commercial capital. We help Margao businesses — retail, services, offices and more — win local customers and grow online.",
 "body":["Margao concentrates South Goa's retail, wholesale, healthcare and professional services, driven largely by resident demand. Winning local search and the Google Map Pack is the top priority here.",
   "Sanctify delivers Margao businesses Google Business Profile optimisation, local SEO and citations, conversion-focused websites and targeted local campaigns — so nearby customers find and choose you first."],
 "industries":["Retail &amp; wholesale","Clinics &amp; healthcare","Offices &amp; services","Restaurants"],
 "nearby":[("colva","Colva"),("cavelossim","Cavelossim"),("ponda","Ponda")],
 "faqs":[["Do you serve small and medium businesses in Margao?","Yes — from local shops and clinics to offices and service providers. We start with high-ROI local SEO and Google Business Profile work tuned to South Goa's largest town."],
   ["How do you help Margao businesses rank locally?","We optimise your Google Business Profile, build local citations and content, and generate reviews so you win 'near me' searches across Margao and South Goa."],
   ["Can you build our website and run ads too?","Absolutely — as a full-service agency we handle web design, SEO, social and paid ads together for coordinated results."]]},

{"slug":"vasco-da-gama","name":"Vasco da Gama","region":"South","img":"loc-vasco.jpg",
 "meta":"Digital marketing agency in Vasco da Gama, Goa — SEO, web design, social media and branding. Sanctify's home base, serving Vasco's businesses, port trade and services.",
 "intro":"Vasco da Gama is our home base — Goa's port city and a busy commercial and industrial centre. We help Vasco businesses across trade, services and hospitality grow online.",
 "body":["Vasco combines port and industrial activity with local retail, services and hospitality. Businesses here serve both residents and a working population, making local visibility and lead capture essential.",
   "As a Vasco-based agency, Sanctify knows this market intimately. We deliver local SEO, Google Business Profile optimisation, conversion-focused websites, social media and lead-gen campaigns for Vasco businesses."],
 "industries":["Trade, logistics &amp; B2B","Retail &amp; services","Clinics &amp; healthcare","Restaurants &amp; hospitality"],
 "nearby":[("margao","Margao"),("colva","Colva"),("panaji","Panaji")],
 "faqs":[["Is Sanctify based in Vasco da Gama?","Yes — Vasco is our home base. We understand the local market deeply and work closely with businesses across the city and wider South Goa."],
   ["Do you work with B2B and trade businesses?","We do — with lead-focused websites, local SEO and targeted campaigns designed to generate qualified B2B and trade enquiries."],
   ["Can you help local shops and clinics in Vasco?","Yes — Google Business Profile optimisation, local SEO and review systems put you in front of nearby customers searching for what you offer."]]},

{"slug":"colva","name":"Colva","region":"South","img":"loc-colva.jpg",
 "meta":"Digital marketing for Colva &amp; Benaulim, South Goa — SEO, social media and booking websites for hotels, restaurants and tourist businesses on South Goa's popular beaches.",
 "intro":"Colva and Benaulim are South Goa's popular beach destinations. We help hotels, restaurants and tourist businesses here stay visible to travellers and convert searches into bookings.",
 "body":["Colva's visitors — many families and domestic tourists — research and book online. Being easy to find, trust and book on mobile is what wins the stay.",
   "We build Colva businesses direct-booking websites, strong local SEO and Google Business Profile presence, social content and seasonal campaigns to fill rooms and tables through the year."],
 "industries":["Hotels &amp; resorts","Restaurants &amp; shacks","Activities &amp; tours","Retail"],
 "nearby":[("margao","Margao"),("cavelossim","Cavelossim"),("palolem","Palolem")],
 "faqs":[["Can you increase direct bookings for my Colva hotel?","Yes — a fast direct-booking website plus local SEO, Google Business Profile and social presence shift bookings to your own channels and cut OTA commissions."],
   ["Do you work with family-focused resorts?","We tailor messaging and campaigns to families and domestic tourists, highlighting the amenities and experiences they search for."],
   ["How do you handle South Goa's seasonality?","We build visibility ahead of peak season and run targeted offers in quieter months to keep occupancy steady."]]},

{"slug":"cavelossim","name":"Cavelossim","region":"South","img":"loc-cavelossim.jpg",
 "meta":"Digital marketing for Cavelossim &amp; Varca, South Goa — premium web design, SEO and social media for luxury resorts and upscale hospitality on South Goa's finest beaches.",
 "intro":"Cavelossim and Varca are home to South Goa's luxury resorts. We help premium hospitality brands here attract higher-value guests and win more direct bookings.",
 "body":["This belt caters to a premium, experience-seeking guest who expects excellence online before they book. Polished websites, photography and reputation are decisive.",
   "Sanctify gives Cavelossim resorts refined, high-converting websites, strong SEO and Google Business Profile presence, elegant social content and precise campaigns that drive premium direct bookings."],
 "industries":["Luxury resorts","Fine dining","Spa &amp; wellness","Destination weddings &amp; events"],
 "nearby":[("colva","Colva"),("palolem","Palolem"),("margao","Margao")],
 "faqs":[["Do you work with luxury resorts in Cavelossim?","Yes — premium web design, photography-led presentation and reputation management are our specialty for this upscale market."],
   ["Can you help with destination weddings and events?","We run targeted campaigns and build dedicated pages to attract wedding and event enquiries from across India and abroad."],
   ["How do you drive more direct bookings?","Through a fast direct-booking website, strong SEO, and campaigns that reward booking direct — reducing reliance on high-commission OTAs."]]},

{"slug":"palolem","name":"Palolem","region":"South","img":"loc-palolem.jpg",
 "meta":"Digital marketing for Palolem &amp; Canacona, South Goa — websites, SEO and social media for beach huts, cafes, stays and tour operators in scenic South Goa.",
 "intro":"Palolem in Canacona is South Goa's scenic crescent-bay destination — beach huts, cafes and tours. We help Palolem businesses reach travellers searching for that laid-back Goa experience.",
 "body":["Palolem draws travellers seeking a quieter, scenic Goa — they discover stays and experiences through Google, Instagram and reviews. Strong visuals and visibility win them.",
   "We help Palolem huts, cafes and operators with booking-friendly websites, local SEO, evocative social content and seasonal campaigns that capture demand across the travel-planning cycle."],
 "industries":["Beach huts &amp; stays","Cafes &amp; restaurants","Tours &amp; activities","Wellness retreats"],
 "nearby":[("cavelossim","Cavelossim"),("colva","Colva"),("margao","Margao")],
 "faqs":[["Can you help my Palolem beach huts get more bookings?","Yes — a booking-friendly website, strong local SEO and evocative social content help travellers find and book you directly across the season."],
   ["Do you create content that captures Palolem's vibe?","We produce scenic, atmospheric photo and video content that reflects Palolem's laid-back appeal and stops the scroll."],
   ["How do you reach travellers planning a South Goa trip?","Through SEO and targeted social campaigns timed to the planning cycle, so you're visible when travellers are researching and deciding."]]},

{"slug":"ponda","name":"Ponda","region":"Central","img":"loc-ponda.jpg",
 "meta":"Digital marketing for Ponda, Goa — local SEO, web design and lead generation for manufacturers, industrial estate businesses, temples-tourism and local services in central Goa.",
 "intro":"Ponda is central Goa's temple town and industrial estate hub. We help Ponda's manufacturers, service businesses and local traders generate visibility and qualified leads online.",
 "body":["Ponda blends industrial estates, manufacturing and B2B activity with local commerce and temple tourism. Businesses here benefit from both local search visibility and lead-focused campaigns.",
   "Sanctify supports Ponda businesses with lead-generation websites, local SEO, Google Business Profile optimisation and targeted B2B and local campaigns — with every enquiry tracked."],
 "industries":["Manufacturing &amp; industrial","B2B &amp; wholesale","Local services &amp; retail","Temple &amp; heritage tourism"],
 "nearby":[("panaji","Panaji"),("margao","Margao"),("porvorim","Porvorim")],
 "faqs":[["Do you work with manufacturers and industrial businesses in Ponda?","Yes — we build lead-focused websites and run B2B campaigns designed to generate qualified enquiries for manufacturers and industrial suppliers."],
   ["Can you help local Ponda shops and services?","We optimise your Google Business Profile and local SEO so nearby customers find you for 'near me' searches, plus build a simple conversion-focused website."],
   ["How do you generate B2B leads?","Through targeted search and LinkedIn/Meta campaigns, dedicated landing pages and clear lead tracking so you know which campaigns deliver."]]},
]
